apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: development
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: wil playground
  # Allow manifests to deploy from the github repo of the project
  sourceRepos:
  - 'https://github.com/cnstll/inception-of-things.git'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc