require 'yaml'

current_dir = File.dirname(File.expand_path(__FILE__))
vagrant_config = YAML.load_file("#{current_dir}/config.yaml")

Vagrant.configure("2") do |config|
  config.vm.define "calleS" do |server|
    server.vm.box = vagrant_config["box"]
    server.vm.hostname = "calleS"
    server.vm.network "private_network", ip: vagrant_config["server"]["ip"]
    server.vm.provider "virtualbox" do |vb|
      vb.name = "calleS"
      vb.memory = 1024
      vb.cpus = 1
    end
  config.ssh.insert_key = false
  end

  config.vm.provision "shell", privileged: false, path: vagrant_config["server"]["script_path"] 
end