require 'yaml'

current_dir = File.dirname(File.expand_path(__FILE__))
vagrant_config = YAML.load_file("#{current_dir}/confs/vagrant/config.yaml")

Vagrant.configure("2") do |config|
  config.vm.define "calleS" do |server|
    server.vm.box = vagrant_config["box"]
    server.vm.hostname = "calleS"
    server.vm.network "private_network", ip: vagrant_config["server"]["ip"], netmask: "255.255.255.0"
    server.vm.synced_folder "confs/", "/home/vagrant/confs/", create: true
    server.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "calleS"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      vb.cpus = 1
      vb.memory = 2048
    end
    server.vm.provision "shell", path: vagrant_config["server"]["script_path"]
  end
end