require 'yaml'

current_dir = File.dirname(File.expand_path(__FILE__))
vagrant_config = YAML.load_file("#{current_dir}/config.yaml")

Vagrant.configure("2") do |config|
  config.vm.define "calleS" do |server|
    server.vm.box = vagrant_config["box"]
    server.vm.hostname = "calleS"
    server.vm.network "private_network", ip: vagrant_config["server"]["ip"]
    server.vm.network "forwarded_port", id: "ssh", guest: 22, host: 2201
    server.ssh.insert_key = false
    # server.ssh.private_key_path = vagrant_config["ssh_private_key_path"]
    server.vm.provider "virtualbox" do |vb|
      vb.name = "calleS"
      vb.memory = 512
      vb.cpus = 1
    end
    server.vm.provision "shell", args: vagrant_config["ssh_private_key_path"], inline: <<-SHELL
      # Install K3s in controller mode
      #curl -sfL https://get.k3s.io | sh -
      echo "Hello from calleS"
      echo "private_key_path used : $1"
      # Copy Kubeconfig to the local machine
      #cp /etc/rancher/k3s/k3s.yaml /vagrant/k3s-controller.yaml
    SHELL
  end

  config.vm.define "calleSW" do |server_worker|
    server_worker.vm.box = vagrant_config["box"]
    server_worker.vm.hostname = "calleSW"
    server_worker.vm.network "private_network", ip: vagrant_config["server_worker"]["ip"]
    server_worker.vm.network "forwarded_port", id: "ssh", guest: 22, host: 2202
    server_worker.ssh.insert_key = false
    # server_worker.ssh.private_key_path = vagrant_config["ssh_private_key_path"]
    server_worker.vm.provider "virtualbox" do |vb|
      vb.name = "calleSW"
      vb.memory = 512
      vb.cpus = 1
    end
    server_worker.vm.provision "shell", inline: <<-SHELL
      # Install K3s in agent mode
      #curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 sh -
      echo "Hello from calleSW"
    SHELL
  end

  # config.vm.provision "shell", args: vagrant_config['ssh_public_key'], inline: <<-SHELL
  #   echo "PUBKEY: $1"
  #   echo "$1"  >> /home/vagrant/.ssh/authorized_keys
  
  # SHELL
end