Vagrant.configure("2") do |config|
  config.vm.box = "$VAGRANT_BOX"
  config.vm.define "calleS" do |server|
    server.vm.network "private_network", type: "static", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "calleS"]
      vb.memory = 512
      vb.cpus = 1
    end
    server.vm.provision "shell", inline: <<-SHELL
      # Install K3s in controller mode
      #curl -sfL https://get.k3s.io | sh -
      echo "Hello from calleS"
      # Copy Kubeconfig to the local machine
      #cp /etc/rancher/k3s/k3s.yaml /vagrant/k3s-controller.yaml
    SHELL
  end

  config.vm.define "calleSW" do |server_worker|
    server_worker.vm.network "private_network", type: "static", ip: "192.168.56.111"
    server_worker.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "calleSW"]
      vb.memory = 512
      vb.cpus = 1
    end
    server_worker.vm.provision "shell", inline: <<-SHELL
      # Install K3s in agent mode
      #curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 sh -
      echo "Hello from calleSW"
    SHELL
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo '$SSH_PUBLIC_KEY' >> /home/vagrant/.ssh/authorized_keys
  SHELL
end