apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
  labels:
    app: app-two
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      containers:
      - name: app-two
        image: paulbouwer/hello-kubernetes:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: "Hello from app2."
        - name: KUBERNETES_NAMESPACE
          value: "K3s"
        - name: KUBERNETES_NODE_NAME
          value: "App2"
---
apiVersion: v1
kind: Service
metadata:
  name: app-two
spec:
  selector:
    app: app-two
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080